### ISSUE TITLE
پروژه

### ISSUE THREAD

**Issue by ghost** [1995parham/TFA#1]
سلام

پروژه فقط شامل طراحی ماشین هست؟ 
تست کیس ها ناقص نیستند؟ چون فقط داریم مشخصات ماشین رو بهش میدیم و هیچ خروجی ازش نخواستیم. تا جایی که یادمه استاد گفتن باید بهش یه سری کلمه بدیم بهمون جواب بده که قبول میکنه این ماشین یا نه؟

**Comment by 1995parham** [comment]
سلام !
پروژه فقط شامل طراحی نرم افزاری برای گرفتن یک ماشین و یک رشته و تشخیص پذیرنده بودن ماشین برای آن رشته است و در ادامه برنامه شما باید بتواند این عمل را برای اشتراک دو ماشین نیز انجام دهد.
تست کیس ها هم شامل ماشین هاست ! فکر میکنم رشته ها را شما باید وارد کنید ولی اگر فرصت کنم چند رشته هم میگذارم
